Add VTRMC problem sets in TeX 1991–1999
Also update the LaTeX workflow to keep going despite errors (though still exit
with an error code at the end if any year's problem or solution build fails),
and display errors as annotations so they're more easily visible.

diff --git a/.github/workflows/latex.yaml b/.github/workflows/latex.yaml
--- a/.github/workflows/latex.yaml
+++ b/.github/workflows/latex.yaml
@@ -44,6 +44,7 @@ jobs:
     - name: Build *.tex files to PDFs
       run: |
         cd vtrmc/tex
+        EXIT_CODE=0
         for year in [1-9]* ; do
           # The begin/end markers enable having collapsible sections in the
           # output, which improves readability.
@@ -52,13 +53,20 @@ jobs:
           # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
 
           echo "::group::VTRMC ${year} problems"
-          make -C "${year}" problems
+          make -C "${year}" problems || {
+            echo "::error::VTRMC ${year} problems failed"
+            EXIT_CODE=$?
+          }
           echo "::endgroup::"
 
           echo "::group::VTRMC ${year} solutions"
-          make -C "${year}" solutions
+          make -C "${year}" solutions || {
+            echo "::error::VTRMC ${year} solutions failed"
+            EXIT_CODE=$?
+          }
           echo "::endgroup::"
         done
+        exit $EXIT_CODE
       env:
         VERBOSE: 1
 
